# SAM/CFN テンプレート

# infra/template.yaml に載せるべき主なリソース：

# AWS::S3::Bucket
  # ArtifactBucket（CodePipeline用）
  # （任意）UploadBucket（S3トリガ用）

# AWS::CodePipeline::Pipeline
  # Source（GitHub/S3）
  # Build（CodeBuild）
  # （Option）Deploy
  # Slack通知は CodeBuild/CodePipelineのステータスをEventBridgeで受ける構成にする

# AWS::CodeBuild::Project
  # Environment（ランタイム、環境変数）
  # Source（CodePipelineから受け取る）
  # Artifacts（CodePipeline返却）

# AWS::IAM::Role（最低3つ）
  # CodePipelineRole
  # CodeBuildRole
  # SlackNotifierLambdaRole

# AWS::Lambda::Function（slack_notifier）
  # イベントソース：EventBridge Rule（CodeBuild/CodePipelineの State Change）
  # 環境変数：
    # SLACK_WEBHOOK_SSM_PARAM_NAME
    # CHANNEL（任意）
    # MENTION_ROLE（任意）

# AWS::Events::Rule
  # CodeBuild / CodePipeline の完了イベントを拾って slack_notifier をInvoke

# AWS::SSM::Parameter（サンプル）
  # Webhookは実際にはユーザーが手動で入れる前提で、テンプレートにはダミー説明だけ。

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  CodePipeline Trigger Template (S3 + GitHub)

Globals:
  Function:
    Runtime: python3.10
    Timeout: 30

Parameters:
  GitHubOwner:
    Type: String
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
  S3UploadBucketName:
    Type: String
  ArtifactBucketName:
    Type: String
  GitHubConnectionArn:
    Type: String
    Description: "ARN of the CodeStar connection to GitHub"

Resources:
  # CodePipelineRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     # TODO: 権限

  # CodeBuildRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     # TODO

  # CodeBuildStatusRule:
  #     Type: AWS::Events::Rule
  #     Properties:
  #       EventPattern:
  #         source:
  #           - "aws.codebuild"
  #         detail-type:
  #           - "CodeBuild Build State Change"
  #         # TODO: detail.status の細かい条件は後で
  #       Targets:
  #         - Arn: !GetAtt SlackNotifierFunction.Arn
  #           Id: SlackNotifierTarget

  # CodePipelineStatusRule:
  #     Type: AWS::Events::Rule
  #     Properties:
  #       EventPattern:
  #         source:
  #           - "aws.CodePipeline"
  #         detail-type:
  #           - "CodePipeline Pipeline State Change"
  #         # TODO: detail.status の細かい条件は後で
  #       Targets:
  #         - Arn: !GetAtt SlackNotifierFunction.Arn
  #           Id: SlackNotifierTarget2

  SlackNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: ../src/slack_notifier/
      Policies:
        - AWSLambdaBasicExecutionRole
        - SSMParameterReadPolicy:
            ParameterName: "amomo/codepipeline/slack_webhook"
        # TODO: CloudWatch Logs 出力（デフォルトOK）
        # TODO: 将来 EventBridge から受信するための最小権限
      Environment:
        Variables:
          SLACK_WEBHOOK_SSM_PARAM_NAME: "/amomo/codepipeline/slack_webhook"

  # Pipeline:
  #   Type: AWS::CodePipeline::Pipeline
  #   Properties:
  #     RoleArn: !GetAtt CodePipelineRole.Arn
  #     ArtifactStore:
  #       Type: S3
  #       Location: !Ref ArtifactBucketName
      
  #     Stages:
  #       - Name: Source
  #         Actions:
  #           - Name: GitHubSource
  #             ActionTypeId:
  #               Category: Source
  #               Owner: AWS
  #               Provider: CodeStarSourceConnection
  #               Version: "1"
  #             Configuration:
  #               ConnectionArn: !Ref GitHubConnectionArn
  #               FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepo}"
  #               BranchName: !Ref GitHubBranch
  #               OutputArtifactFormat: CODE_ZIP
  #             OutputArtifacts:
  #               - Name: SourceOutput
  #             RunOrder: 1

  #       - Name: Build
  #         Actions:
  #           - Name: CodeBuild
  #             ActionTypeId:
  #               Category: Build
  #               Owner: AWS
  #               Provider: CodeBuild
  #               Version: "1"
  #             InputArtifacts:
  #               - Name: SourceOutput
  #             OutputArtifacts:
  #               - Name: BuildOutput
  #             Configuration:
  #               ProjectName: !Ref BuildProject
  #             RunOrder: 1

  #       - Name: Notify
  #         Actions: []
  #         # 後でSlack通知を EventBridge 経由にするので空でOK

  # BuildProject:
  #   Type: AWS::CodeBuild::Project
  #   Properties:
  #     Name: !Sub "${AWS::StackName}-build"
  #     ServiceRole: !GetAtt CodeBuildRole.Arn
  #     Artifacts:
  #       Type: CODEPIPELINE
  #     Environment:
  #       Type: LINUX_CONTAINER
  #       ComputeType: BUILD_GENERAL1_SMALL
  #       Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  #       EnvironmentVariables:
  #         - Name: ENV
  #           Value: dev
  #         # TODO: 他に必要なら後で追加
  #     Source:
  #       Type: CODEPIPELINE
  #     # TODO: キャッシュやTimeoutは後で調整

Outputs:
  SlackNotifierFunctionName:
    Description: "Name of the Slack notifier Lambda function"
    Value: !Ref SlackNotifierFunction
  # PipelineName:
  #   Value: !Ref Pipeline
